### ISSUE TITLE
Problem z wyświetlaniem kalendarza.

### ISSUE THREAD

**Issue by tiwek** [Antoni-Czaplicki/vulcan-for-hassio#36]
Zauważyłem dość dziwny problem.
Przy wyświetlaniu kalendarza przy pomocy karty [https://github.com/totaldebug/atomic-calendar-revive](Atomic Calendar Revive) w trybie Event danego dnia wyświtlają się również wpisy z  dnia poprzedniego. Nie wiem, czy to problem dodatku kalendarza, ale z kalendarzem google tego problemu nie ma

```
type: custom:atomic-calendar-revive
enableModeChange: true
entities:
  - entity: calendar.XXX
    name: Vulcan calendar
    maxDaysToShow: 1
firstDayOfWeek: 1
maxDaysToShow: 7
refreshInterval: 60
disableLocationLink: true
showFullDayProgress: false
showHiddenText: false
showWeekNumber: false
showCalendarName: false
showEventIcon: false
showNoEventsForToday: false
disableEventLink: false
showWeekDay: true
showMonth: true
dimFinishedEvents: true
calShowDescription: false
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLocationLink: false
disableCalLink: false
```
